blank_issues_enabled: false
contact_links:
  - name: Question & Discussion
    url: https://discord.gg/V7VzKjqhKX
    about: Post your questions and join the discussion. You can participate in chats on every channel.
