name: Feature Request
description: Request a new feature or enhancement.
type: 'feature'
title: 'Feature: '
body:
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        >Please check if there are any requests for already defined functions. It may already be defined and working!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please let us know about new features and improvements.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information (Comments)
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
