spring:
  application:
    name: base
  datasource:
    url: jdbc:postgresql://localhost:5432/iowiki
    username: local
    password: local
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy